inherit_from: .rubocop_yast_style.yml

# Getting a grip on completely insane rubocop defaults.
#
# Seriously, who comes up with those?  Are they doing any serious work with
# Ruby, or they you just playing around?

# Forbidding for loops completely does not improve code
Style/For:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/Alias:
  Enabled: false

Style/UnneededInterpolation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 10

Metrics/AbcSize:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/MethodLength:
  Max: 50

Metrics/BlockLength:
  Max: 2000

